import type { DayHours, Listing } from '../types';
import { categoryLabel } from '../categories';
import { cityLabel, CITY_COORDS } from '../cities';
import { initialOf } from '../format';

/**
 * Built-in seed dataset — the permanent fallback (§5.4). The site renders this
 * until the live JetEngine API is wired. Mix of premium (cover + gallery +
 * category block + verified) and free (no cover, no whatsapp) businesses across
 * real Paraguayan cities. All images are local first-party SVGs in /public/seed.
 */

// Far-future timestamp so premium listings stay premium in the seed.
const PREMIUM = Math.floor(new Date('2030-01-01T00:00:00Z').getTime() / 1000);

// Hours helpers (America/Asuncion wall clock).
const r = (open: string, close: string) => ({ open, close });
type R = { open: string; close: string };
function days(list: { d: DayHours['day']; ranges: R[] }[]): DayHours[] {
  return list.map(({ d, ranges }) => ({ day: d, ranges }));
}
/** Mon–Sat single shift. */
const monSat = (open: string, close: string): DayHours[] =>
  days([1, 2, 3, 4, 5, 6].map((d) => ({ d: d as DayHours['day'], ranges: [r(open, close)] })));
/** Restaurant split shift Tue–Sun. */
const restaurantHours: DayHours[] = days([
  { d: 2, ranges: [r('11:00', '15:00'), r('19:00', '23:00')] },
  { d: 3, ranges: [r('11:00', '15:00'), r('19:00', '23:00')] },
  { d: 4, ranges: [r('11:00', '15:00'), r('19:00', '23:00')] },
  { d: 5, ranges: [r('11:00', '15:00'), r('19:00', '00:00')] },
  { d: 6, ranges: [r('11:00', '15:00'), r('19:00', '00:00')] },
  { d: 0, ranges: [r('11:00', '16:00')] },
]);

export type Seed = Omit<Listing, 'categoriaLabel' | 'ciudadLabel' | 'logoInitial' | 'lat' | 'lng'> &
  Partial<Pick<Listing, 'lat' | 'lng'>>;

const SEED: Seed[] = [
  // ---- Restaurantes y cafés ----
  {
    id: 'r1',
    slug: 'nande-cocina',
    name: 'Ñandé Cocina',
    categoria: 'restaurantes',
    subtitle: 'Cocina paraguaya',
    description:
      'Cocina paraguaya de raíz en el corazón de Villa Morra. Recetas de la abuela, fuego a leña y productos de chacra. Ambiente cálido para almuerzos largos y cenas con amigos, con patio interno y música en vivo los fines de semana.',
    ciudad: 'asuncion',
    zona: 'Villa Morra',
    address: 'Av. España 1234 c/ Brasilia, Villa Morra',
    phone: '021 584 220',
    whatsapp: '595981584220',
    email: 'hola@nandecocina.com.py',
    website: 'https://nandecocina.com.py',
    instagram: 'nandecocina',
    coverImage: '/seed/food-1.svg',
    gallery: ['/seed/food-1.svg', '/seed/food-2.svg', '/seed/food-3.svg', '/seed/warm-1.svg'],
    hours: restaurantHours,
    especialidades: ['Sopa paraguaya', 'Chipa guasú', 'Mbejú', 'Asado a la estaca', 'Bori-bori'],
    destacadoItem: {
      title: 'Menú del día',
      desc: 'Entrada + plato principal + postre · de martes a viernes',
      price: '₲ 65.000',
      image: '/seed/food-2.svg',
    },
    verified: true,
    premiumUntil: PREMIUM,
    yearsActive: 8,
    avgResponseMins: 15,
  },
  {
    id: 'r2',
    slug: 'la-cocina-de-tere',
    name: 'La Cocina de Tere',
    categoria: 'restaurantes',
    subtitle: 'Comida casera',
    description: 'Almuerzos caseros y minutas en Recoleta. Porciones generosas y precios justos.',
    ciudad: 'asuncion',
    zona: 'Recoleta',
    address: 'Sucre 856, Recoleta',
    phone: '021 612 030',
    coverImage: '/seed/food-3.svg',
    hours: monSat('11:00', '15:00'),
    verified: false,
  },
  {
    id: 'r3',
    slug: 'mburicao-grill',
    name: 'Mburicaó Grill',
    categoria: 'restaurantes',
    subtitle: 'Parrilla',
    description: 'Parrilla y asados al estilo paraguayo en Las Mercedes.',
    ciudad: 'asuncion',
    zona: 'Las Mercedes',
    address: 'Mariscal López 2010',
    phone: '021 224 115',
    hours: restaurantHours,
    verified: false,
  },
  {
    id: 'r4',
    slug: 'cafe-del-parana',
    name: 'Café del Paraná',
    categoria: 'restaurantes',
    subtitle: 'Café de especialidad',
    description:
      'Café de especialidad, brunch y reposterÍa artesanal frente a la costanera. Tostado propio y opciones sin gluten.',
    ciudad: 'encarnacion',
    zona: 'Centro',
    address: 'Av. Costanera 145',
    phone: '071 205 880',
    whatsapp: '595985205880',
    instagram: 'cafedelparana',
    coverImage: '/seed/warm-2.svg',
    gallery: ['/seed/warm-2.svg', '/seed/food-2.svg', '/seed/warm-3.svg'],
    hours: monSat('07:30', '20:00'),
    especialidades: ['Café de origen', 'Brunch', 'Medialunas', 'Cheesecake'],
    destacadoItem: { title: 'Desayuno completo', desc: 'Café + jugo + tostado + fruta', price: '₲ 38.000' },
    verified: true,
    premiumUntil: PREMIUM,
    yearsActive: 4,
    avgResponseMins: 20,
  },

  // ---- Tiendas y comercios ----
  {
    id: 't1',
    slug: 'tienda-mandiyu',
    name: 'Tienda Mandi’yú',
    categoria: 'tiendas',
    subtitle: 'Ropa y ao po’í',
    description:
      'Indumentaria y artesanía en ao po’í y encaje ju. Diseños contemporáneos hechos por artesanas paraguayas.',
    ciudad: 'san-lorenzo',
    zona: 'Centro',
    address: 'Mcal. Estigarribia 1450',
    phone: '021 570 410',
    whatsapp: '595971570410',
    instagram: 'tiendamandiyu',
    coverImage: '/seed/shop-1.svg',
    gallery: ['/seed/shop-1.svg', '/seed/shop-2.svg', '/seed/shop-3.svg'],
    hours: monSat('08:00', '18:30'),
    productos: [
      { title: 'Blusa ao po’í', price: '₲ 180.000', image: '/seed/shop-2.svg' },
      { title: 'Camisa de lino', price: '₲ 220.000', image: '/seed/shop-3.svg' },
      { title: 'Mantel bordado', price: '₲ 350.000', image: '/seed/shop-1.svg' },
    ],
    verified: true,
    premiumUntil: PREMIUM,
    yearsActive: 12,
    avgResponseMins: 30,
  },
  {
    id: 't2',
    slug: 'libreria-guarani',
    name: 'Librería Guaraní',
    categoria: 'tiendas',
    subtitle: 'Librería y papelería',
    description: 'Libros, útiles escolares y papelería en pleno centro de Asunción.',
    ciudad: 'asuncion',
    zona: 'Centro',
    address: 'Palma 540',
    phone: '021 449 700',
    hours: monSat('08:00', '18:00'),
    verified: false,
  },
  {
    id: 't3',
    slug: 'almacen-dona-blanca',
    name: 'Almacén Doña Blanca',
    categoria: 'tiendas',
    subtitle: 'Almacén de barrio',
    description: 'Almacén de barrio con productos frescos y atención de toda la vida.',
    ciudad: 'capiata',
    zona: 'Km 20',
    address: 'Ruta 2 Km 20',
    phone: '0228 633 410',
    hours: days([0, 1, 2, 3, 4, 5, 6].map((d) => ({ d: d as DayHours['day'], ranges: [r('07:00', '21:00')] }))),
    verified: false,
  },

  // ---- Servicios para el hogar ----
  {
    id: 'h1',
    slug: 'clima-confort-aire',
    name: 'Clima Confort',
    categoria: 'hogar',
    subtitle: 'Aire acondicionado',
    description:
      'Instalación, carga de gas y mantenimiento de aires acondicionados split. Servicio a domicilio en Gran Asunción con garantía escrita.',
    ciudad: 'fernando-de-la-mora',
    zona: 'Zona Sur',
    address: 'Tte. Fariña 880',
    phone: '021 503 220',
    whatsapp: '595981503220',
    coverImage: '/seed/service-1.svg',
    gallery: ['/seed/service-1.svg', '/seed/service-2.svg'],
    hours: monSat('08:00', '17:00'),
    servicios: [
      { title: 'Instalación de split', desc: 'Hasta 18.000 BTU, incluye soportes' },
      { title: 'Carga de gas', desc: 'R410 / R22 con detección de fugas' },
      { title: 'Mantenimiento preventivo', desc: 'Limpieza de filtros y serpentina' },
    ],
    verified: true,
    premiumUntil: PREMIUM,
    yearsActive: 9,
    avgResponseMins: 25,
  },
  {
    id: 'h2',
    slug: 'plomeria-rapida-acosta',
    name: 'Plomería Rápida Acosta',
    categoria: 'hogar',
    subtitle: 'Plomería',
    description: 'Destapaciones, reparación de cañerías y colocación de grifería. Atención el mismo día.',
    ciudad: 'luque',
    zona: 'Centro',
    address: 'Cap. Brizuela 230',
    phone: '021 645 100',
    hours: monSat('07:30', '18:00'),
    verified: false,
  },
  {
    id: 'h3',
    slug: 'jardines-del-este',
    name: 'Jardines del Este',
    categoria: 'hogar',
    subtitle: 'Jardinería y paisajismo',
    description: 'Diseño y mantenimiento de jardines, poda y colocación de césped.',
    ciudad: 'ciudad-del-este',
    zona: 'Área 1',
    address: 'Av. Pioneros del Este 1200',
    phone: '061 570 990',
    hours: monSat('07:00', '16:00'),
    verified: false,
  },

  // ---- Talleres y mecánica ----
  {
    id: 'm1',
    slug: 'taller-velocidad-luque',
    name: 'Taller Velocidad',
    categoria: 'talleres',
    subtitle: 'Mecánica general',
    description:
      'Mecánica general, scanner computarizado y servicio de frenos. Atendido por su dueño con repuestos garantizados.',
    ciudad: 'luque',
    zona: 'Microcentro',
    address: 'Gral. Aquino 540',
    phone: '021 642 880',
    whatsapp: '595982642880',
    coverImage: '/seed/service-3.svg',
    gallery: ['/seed/service-3.svg', '/seed/service-1.svg'],
    hours: monSat('07:30', '17:30'),
    servicios: [
      { title: 'Scanner computarizado', desc: 'Diagnóstico de fallas electrónicas' },
      { title: 'Service completo', desc: 'Aceite, filtros y revisión de 20 puntos' },
      { title: 'Frenos', desc: 'Pastillas, discos y purgado' },
    ],
    verified: true,
    premiumUntil: PREMIUM,
    yearsActive: 15,
    avgResponseMins: 40,
  },
  {
    id: 'm2',
    slug: 'gomeria-el-rayo',
    name: 'Gomería El Rayo',
    categoria: 'talleres',
    subtitle: 'Gomería',
    description: 'Reparación y venta de cubiertas, alineación y balanceo.',
    ciudad: 'capiata',
    zona: 'Ruta 2',
    address: 'Ruta 2 Km 22,5',
    phone: '0228 631 200',
    hours: days([0, 1, 2, 3, 4, 5, 6].map((d) => ({ d: d as DayHours['day'], ranges: [r('07:00', '19:00')] }))),
    verified: false,
  },

  // ---- Salud ----
  {
    id: 's1',
    slug: 'centro-medico-sanar',
    name: 'Centro Médico Sanar',
    categoria: 'salud',
    subtitle: 'Consultorios médicos',
    description:
      'Consultorios de clínica médica, pediatría y cardiología. Laboratorio propio y atención con turnos por WhatsApp.',
    ciudad: 'asuncion',
    zona: 'Barrio Jara',
    address: 'Dr. Facundo Insfrán 765',
    phone: '021 226 540',
    whatsapp: '595961226540',
    website: 'https://sanar.com.py',
    coverImage: '/seed/health-1.svg',
    gallery: ['/seed/health-1.svg', '/seed/health-2.svg'],
    hours: monSat('07:00', '19:00'),
    servicios: [
      { title: 'Clínica médica', desc: 'Consultas y chequeos generales' },
      { title: 'Pediatría', desc: 'Control de niño sano y vacunas' },
      { title: 'Laboratorio', desc: 'Análisis clínicos con resultados en 24h' },
    ],
    verified: true,
    premiumUntil: PREMIUM,
    yearsActive: 11,
    avgResponseMins: 18,
  },
  {
    id: 's2',
    slug: 'farmacia-guadalupe',
    name: 'Farmacia Guadalupe',
    categoria: 'salud',
    subtitle: 'Farmacia',
    description: 'Farmacia de turno con servicio de delivery en Lambaré.',
    ciudad: 'lambare',
    zona: 'Centro',
    address: 'Cacique Lambaré 410',
    phone: '021 906 220',
    hours: days([0, 1, 2, 3, 4, 5, 6].map((d) => ({ d: d as DayHours['day'], ranges: [r('07:00', '22:00')] }))),
    verified: false,
  },
  {
    id: 's3',
    slug: 'kinesiologia-movimiento',
    name: 'Kinesiología Movimiento',
    categoria: 'salud',
    subtitle: 'Fisioterapia',
    description: 'Rehabilitación deportiva y terapia física personalizada.',
    ciudad: 'san-lorenzo',
    zona: 'Centro',
    address: 'Saturio Ríos 990',
    phone: '021 574 330',
    hours: monSat('07:00', '20:00'),
    verified: false,
  },

  // ---- Belleza y estética ----
  {
    id: 'b1',
    slug: 'studio-bella-luque',
    name: 'Studio Bella',
    categoria: 'belleza',
    subtitle: 'Peluquería y estética',
    description:
      'Peluquería, coloración, uñas y tratamientos faciales. Reservá tu turno por WhatsApp y elegí tu profesional.',
    ciudad: 'luque',
    zona: 'Centro',
    address: 'Mcal. Estigarribia 320',
    phone: '021 643 770',
    whatsapp: '595983643770',
    instagram: 'studiobella.py',
    coverImage: '/seed/warm-3.svg',
    gallery: ['/seed/warm-3.svg', '/seed/warm-1.svg', '/seed/shop-2.svg'],
    hours: monSat('09:00', '19:00'),
    servicios: [
      { title: 'Corte y brushing', desc: 'Lavado, corte y peinado' },
      { title: 'Coloración', desc: 'Tintura, mechas y balayage' },
      { title: 'Uñas', desc: 'Esculpidas y semipermanente' },
    ],
    verified: true,
    premiumUntil: PREMIUM,
    yearsActive: 6,
    avgResponseMins: 10,
  },
  {
    id: 'b2',
    slug: 'barberia-don-pelo',
    name: 'Barbería Don Pelo',
    categoria: 'belleza',
    subtitle: 'Barbería',
    description: 'Cortes clásicos y modernos, arreglo de barba al ras.',
    ciudad: 'fernando-de-la-mora',
    zona: 'Zona Norte',
    address: 'Ruta Mariscal Estigarribia 1820',
    phone: '021 514 660',
    hours: monSat('09:00', '20:00'),
    verified: false,
  },

  // ---- Profesionales ----
  {
    id: 'p1',
    slug: 'estudio-contable-figari',
    name: 'Estudio Contable Figari',
    categoria: 'profesionales',
    subtitle: 'Contabilidad y tributos',
    description:
      'Asesoría contable e impositiva para pymes y monotributistas. Liquidación de IVA, IRP y gestión ante la SET.',
    ciudad: 'asuncion',
    zona: 'Centro',
    address: 'Estrella 680, piso 3',
    phone: '021 493 110',
    whatsapp: '595971493110',
    email: 'contacto@figari.com.py',
    website: 'https://figari.com.py',
    coverImage: '/seed/tech-2.svg',
    hours: monSat('08:00', '17:00'),
    servicios: [
      { title: 'Liquidación de impuestos', desc: 'IVA, IRP e IRE mensual' },
      { title: 'Constitución de empresas', desc: 'SRL, SA y EAS llave en mano' },
      { title: 'Asesoría laboral', desc: 'IPS, planillas y contratos' },
    ],
    verified: true,
    premiumUntil: PREMIUM,
    yearsActive: 14,
    avgResponseMins: 60,
  },
  {
    id: 'p2',
    slug: 'estudio-juridico-benitez',
    name: 'Estudio Jurídico Benítez',
    categoria: 'profesionales',
    subtitle: 'Abogados',
    description: 'Derecho civil, laboral y de familia. Primera consulta sin cargo.',
    ciudad: 'encarnacion',
    zona: 'Centro',
    address: 'Mallorquín 540',
    phone: '071 204 330',
    hours: monSat('08:00', '16:00'),
    verified: false,
  },

  // ---- Ferreterías ----
  {
    id: 'f1',
    slug: 'ferreteria-el-tornillo',
    name: 'Ferretería El Tornillo',
    categoria: 'ferreterias',
    subtitle: 'Ferretería y construcción',
    description:
      'Materiales de construcción, herramientas eléctricas y pinturas. Entrega a obra en Gran Asunción.',
    ciudad: 'capiata',
    zona: 'Ruta 2',
    address: 'Ruta 2 Km 19',
    phone: '0228 632 900',
    whatsapp: '595984632900',
    coverImage: '/seed/shop-3.svg',
    gallery: ['/seed/shop-3.svg', '/seed/shop-1.svg'],
    hours: monSat('07:00', '18:00'),
    productos: [
      { title: 'Taladro percutor', price: '₲ 420.000' },
      { title: 'Bolsa de cemento 50kg', price: '₲ 48.000' },
      { title: 'Pintura látex 20L', price: '₲ 310.000' },
    ],
    verified: true,
    premiumUntil: PREMIUM,
    yearsActive: 18,
    avgResponseMins: 35,
  },
  {
    id: 'f2',
    slug: 'ferreteria-central-cde',
    name: 'Ferretería Central',
    categoria: 'ferreterias',
    subtitle: 'Ferretería',
    description: 'Todo para electricidad, plomería y herrajes en Ciudad del Este.',
    ciudad: 'ciudad-del-este',
    zona: 'Microcentro',
    address: 'Av. Adrián Jara 765',
    phone: '061 512 040',
    hours: monSat('07:30', '18:00'),
    verified: false,
  },

  // ---- Veterinarias ----
  {
    id: 'v1',
    slug: 'veterinaria-patitas',
    name: 'Veterinaria Patitas',
    categoria: 'veterinarias',
    subtitle: 'Clínica veterinaria',
    description:
      'Consultas, vacunación, cirugía y peluquería canina. Urgencias coordinadas por WhatsApp.',
    ciudad: 'lambare',
    zona: 'Centro',
    address: 'Cerro Corá 1240',
    phone: '021 907 880',
    whatsapp: '595985907880',
    instagram: 'vetpatitas',
    coverImage: '/seed/service-2.svg',
    gallery: ['/seed/service-2.svg', '/seed/service-3.svg'],
    hours: monSat('08:00', '19:00'),
    servicios: [
      { title: 'Consulta clínica', desc: 'Diagnóstico y tratamiento' },
      { title: 'Vacunación', desc: 'Plan sanitario completo' },
      { title: 'Peluquería', desc: 'Baño y corte para perros y gatos' },
    ],
    verified: true,
    premiumUntil: PREMIUM,
    yearsActive: 7,
    avgResponseMins: 12,
  },
  {
    id: 'v2',
    slug: 'agroveterinaria-el-campo',
    name: 'Agroveterinaria El Campo',
    categoria: 'veterinarias',
    subtitle: 'Agroveterinaria',
    description: 'Productos para animales de granja y mascotas, balanceados y sanidad animal.',
    ciudad: 'san-lorenzo',
    zona: 'Ruta 1',
    address: 'Ruta 1 Km 12',
    phone: '021 576 220',
    hours: monSat('07:00', '17:30'),
    verified: false,
  },

  // ---- Tecnología ----
  {
    id: 'tec1',
    slug: 'tecno-soluciones-cde',
    name: 'Tecno Soluciones',
    categoria: 'tecnologia',
    subtitle: 'Servicio técnico y venta',
    description:
      'Reparación de notebooks y celulares, venta de accesorios e instalación de redes. Diagnóstico sin cargo.',
    ciudad: 'ciudad-del-este',
    zona: 'Shopping del Este',
    address: 'Av. San Blas 980',
    phone: '061 571 220',
    whatsapp: '595986571220',
    website: 'https://tecnosoluciones.com.py',
    coverImage: '/seed/tech-1.svg',
    gallery: ['/seed/tech-1.svg', '/seed/tech-3.svg', '/seed/tech-2.svg'],
    hours: monSat('08:30', '18:30'),
    productos: [
      { title: 'Cambio de pantalla celular', price: '₲ 250.000' },
      { title: 'Limpieza de notebook', price: '₲ 120.000' },
      { title: 'Instalación de red WiFi', price: '₲ 350.000' },
    ],
    verified: true,
    premiumUntil: PREMIUM,
    yearsActive: 5,
    avgResponseMins: 22,
  },
  {
    id: 'tec2',
    slug: 'celulandia-asuncion',
    name: 'Celulandia',
    categoria: 'tecnologia',
    subtitle: 'Accesorios y celulares',
    description: 'Venta de celulares, accesorios y reparaciones express.',
    ciudad: 'asuncion',
    zona: 'Mercado 4',
    address: 'Pettirossi 1320',
    phone: '021 392 110',
    hours: monSat('08:00', '18:00'),
    verified: false,
  },

  // ---- New listings (cover photos in /public/businesses; see that README) ----
  // Verified across the board; Destacado (premium) for dentista, gruas, asado, obra.
  {
    id: 's4',
    slug: 'dentista-paraguay',
    name: 'Dentista Paraguay',
    categoria: 'salud',
    subtitle: 'Consultorio odontológico',
    description:
      'Odontología general y estética en el centro de Asunción. Limpieza, ortodoncia, implantes y blanqueamiento con turnos coordinados por WhatsApp.',
    ciudad: 'asuncion',
    zona: 'Centro',
    address: 'Palma 480, Centro',
    phone: '021 445 780',
    whatsapp: '595971445780',
    email: 'turnos@dentistaparaguay.com.py',
    coverImage: '/businesses/dentista.svg',
    gallery: ['/businesses/dentista.svg'],
    hours: monSat('08:00', '18:00'),
    especialidades: ['Limpieza', 'Ortodoncia', 'Implantes', 'Blanqueamiento', 'Endodoncia'],
    servicios: [
      { title: 'Consulta y diagnóstico', desc: 'Evaluación clínica y plan de tratamiento' },
      { title: 'Ortodoncia', desc: 'Brackets metálicos y estéticos' },
      { title: 'Implantes', desc: 'Rehabilitación con prótesis fija' },
    ],
    verified: true,
    premiumUntil: PREMIUM,
  },
  {
    id: 't4',
    slug: 'floreria-paraguay',
    name: 'Florería Paraguay',
    categoria: 'tiendas',
    subtitle: 'Florería y arreglos',
    description: 'Ramos, arreglos florales y plantas para toda ocasión en Villa Morra. Envíos a domicilio.',
    ciudad: 'asuncion',
    zona: 'Villa Morra',
    address: 'Av. San Martín 1120, Villa Morra',
    phone: '021 601 240',
    whatsapp: '595981601240',
    coverImage: '/businesses/floreria.svg',
    hours: monSat('08:00', '19:00'),
    verified: true,
  },
  {
    id: 'h4',
    slug: 'gruas-paraguay',
    name: 'Grúas Paraguay',
    categoria: 'hogar',
    subtitle: 'Grúas y remolques',
    description:
      'Servicio de grúas y auxilio mecánico 24 horas en Gran Asunción. Traslado de vehículos, remolques y asistencia en ruta.',
    ciudad: 'fernando-de-la-mora',
    zona: 'Zona Sur',
    address: 'Ruta Mcal. Estigarribia 2450, Zona Sur',
    phone: '021 510 900',
    whatsapp: '595981510900',
    coverImage: '/businesses/gruas.svg',
    gallery: ['/businesses/gruas.svg'],
    hours: days([0, 1, 2, 3, 4, 5, 6].map((d) => ({ d: d as DayHours['day'], ranges: [r('00:00', '23:59')] }))),
    servicios: [
      { title: 'Auxilio 24 horas', desc: 'Salida inmediata en Gran Asunción' },
      { title: 'Traslado de vehículos', desc: 'Autos, camionetas y utilitarios' },
      { title: 'Asistencia en ruta', desc: 'Remolque y cambio de rueda' },
    ],
    verified: true,
    premiumUntil: PREMIUM,
  },
  {
    id: 'v3',
    slug: 'mascota-paraguay',
    name: 'Mascota Paraguay',
    categoria: 'veterinarias',
    subtitle: 'Pet shop y veterinaria',
    description: 'Alimentos, accesorios y atención veterinaria para tu mascota en Recoleta.',
    ciudad: 'asuncion',
    zona: 'Recoleta',
    address: 'Andrade 765, Recoleta',
    phone: '021 664 310',
    whatsapp: '595981664310',
    coverImage: '/businesses/mascota.svg',
    hours: monSat('08:30', '19:00'),
    verified: true,
  },
  {
    id: 'm3',
    slug: 'moto-paraguay',
    name: 'Moto Paraguay',
    categoria: 'talleres',
    subtitle: 'Taller de motos',
    description: 'Service, repuestos y reparación de motos en Luque. Atención rápida y repuestos garantizados.',
    ciudad: 'luque',
    zona: 'Centro',
    address: 'Gral. Aquino 880, Luque',
    phone: '021 648 550',
    whatsapp: '595982648550',
    coverImage: '/businesses/moto.svg',
    hours: monSat('07:30', '18:00'),
    verified: true,
  },
  {
    id: 'r5',
    slug: 'asado-paraguay',
    name: 'Asado Paraguay',
    categoria: 'restaurantes',
    subtitle: 'Parrilla y asados',
    description:
      'Asado a la leña, achuras y cortes paraguayos en Barrio Obrero. Ambiente familiar, mesa larga y fuego a la vista.',
    ciudad: 'asuncion',
    zona: 'Barrio Obrero',
    address: 'Dr. Nicanor Torales 540, Barrio Obrero',
    phone: '021 372 660',
    whatsapp: '595985372660',
    coverImage: '/businesses/asado.svg',
    gallery: ['/businesses/asado.svg'],
    hours: restaurantHours,
    especialidades: ['Asado a la estaca', 'Costilla a la leña', 'Chorizo', 'Vacío', 'Mandioca'],
    destacadoItem: {
      title: 'Parrillada completa',
      desc: 'Cortes surtidos + guarniciones · para 2 personas',
      price: '₲ 120.000',
    },
    verified: true,
    premiumUntil: PREMIUM,
  },
  {
    id: 't5',
    slug: 'ropa-paraguay',
    name: 'Ropa Paraguay',
    categoria: 'tiendas',
    subtitle: 'Indumentaria',
    description: 'Ropa para dama, caballero y niños en pleno centro de Asunción. Nuevas colecciones cada temporada.',
    ciudad: 'asuncion',
    zona: 'Centro',
    address: 'Palma 620, Centro',
    phone: '021 447 990',
    whatsapp: '595981447990',
    coverImage: '/businesses/ropa.svg',
    hours: monSat('08:00', '18:30'),
    verified: true,
  },
  {
    id: 'm4',
    slug: 'obra-paraguay',
    name: 'Obra Paraguay',
    categoria: 'talleres',
    subtitle: 'Herrería y obras metálicas',
    description:
      'Herrería, soldadura y estructuras metálicas sobre Ruta 2. Portones, rejas, tinglados y trabajos a medida.',
    ciudad: 'capiata',
    zona: 'Ruta 2',
    address: 'Ruta 2 Km 21, Capiatá',
    phone: '0228 634 120',
    whatsapp: '595984634120',
    coverImage: '/businesses/obra.svg',
    gallery: ['/businesses/obra.svg'],
    hours: monSat('07:00', '17:00'),
    servicios: [
      { title: 'Portones y rejas', desc: 'Diseño, fabricación y colocación' },
      { title: 'Estructuras metálicas', desc: 'Tinglados y entrepisos' },
      { title: 'Soldadura a domicilio', desc: 'Reparaciones y trabajos a medida' },
    ],
    verified: true,
    premiumUntil: PREMIUM,
  },
];

/**
 * The raw seed rows, before derived fields are filled in. The DB importer reads
 * this rather than SEED_LISTINGS so it never persists a derived value (the
 * city-centre coordinate fallback in particular) as if it were a fact about the
 * business.
 */
export const SEED_RAW: readonly Seed[] = SEED;

/** Materialise derived fields (labels, initial, coords) once at module load. */
export const SEED_LISTINGS: Listing[] = SEED.map((s) => {
  const coords = s.lat != null && s.lng != null ? { lat: s.lat, lng: s.lng } : CITY_COORDS[s.ciudad];
  return {
    ...s,
    categoriaLabel: categoryLabel(s.categoria),
    ciudadLabel: cityLabel(s.ciudad),
    logoInitial: initialOf(s.name),
    lat: coords?.lat,
    lng: coords?.lng,
  };
});
